### ISSUE TITLE
Create Arraylake prototype

### ISSUE THREAD

**Issue by kabilar** [lincbrain/linc-archive#102]
- [ ] Create example script with the following operations
- [ ] Open Zarr dataset from DANDI S3 bucket (e.g. Zarr dataset from [Dandiset 108](https://dandiarchive.org/dandiset/000108/draft/files?location=sub-MITU01%2Fses-20210626h17m19s58%2Fmicr&page=1) or [Dandiset 26](https://dandiarchive.org/dandiset/000026/draft/files?location=sub-I58%2Fses-Hip-CT%2Fmicr&page=1)) 
- [ ] Create commit into ArrayLake repository (i.e. `s3://arraylake-sandbox` S3 bucket)
- [ ] Access Zarr dataset from ArrayLake and perform operation (e.g. Gaussian smoothing filter)
- [ ] Create commit into ArrayLake repository
- [ ] (Optionally) list web addresses for each commit
- [ ] Benchmark read and write operations
- [ ] Create a list of feedback

**Comment by aaronkanzer** [comment]
Hosting relevant code here: https://github.com/lincbrain/linc-zarr-testing
