### ISSUE TITLE
Remove `auto-add-issues.yml` GitHub workflow

### ISSUE THREAD

**Issue by kabilar** [lincbrain/linc-archive#117]
Please remove the [auto-add-issues.yml](https://github.com/lincbrain/linc-archive/blob/master/.github/workflows/auto-add-issues.yml) workflow from the `linc-archive` fork.  This workflow is only needed on the upstream DANDI fork.  Thank you.

**Comment by aaronkanzer** [comment]
See code here: https://github.com/lincbrain/linc-archive/pull/118

Just took care of this quickly, as I saw a notification in my email -- going to close

**Comment by kabilar** [comment]
Thank you, Aaron.
