### ISSUE TITLE
Download command for published versions displays the resource identifier with the `DANDI` prefix

### ISSUE THREAD

**Issue by kabilar** [lincbrain/linc-archive#163]
On production (i.e. lincbrain.org), the download command for published versions displays the resource identifier with the `DANDI` prefix (e.g. `lincbrain download DANDI:000005/0.240423.1444`).  Should we update this prefix from `DANDI` to `LINCBRAIN`?  We may also have to update the `lincbrain-cli`, but not sure what else might break.

On staging, the download command for published versions also displays the `DANDI` prefix.  Perhaps we should update the prefix to `LINCBRAIN-STAGING`, or something else?

Thank you.

cc @aaronkanzer

**Comment by aaronkanzer** [comment]
@kabilar unfortunately, this naming convention is validated via `dandischema`

• https://github.com/dandi/dandi-schema/blob/be57e138505819a46475f8f5a590e6f6b00cd1b2/dandischema/models.py#L53

• https://github.com/dandi/dandi-schema/blob/be57e138505819a46475f8f5a590e6f6b00cd1b2/dandischema/models.py#L1588-L1593

Not sure how you'd like to proceed -- seems that we'd have to break some validation/do a bit more refactoring than necessary for a non-feature here.

**Comment by kabilar** [comment]
Thanks for looking into this, Aaron.  Now that I recall there is an issue on the DANDI Org that discusses this item.  I will ping that issue.  Let's defer to the DANDI team on how to best approach.

**Comment by kabilar** [comment]
Closing as we updated the UI in #276 to use the URL and not the `DANDI` resource identifier.
