### ISSUE TITLE
Automate deployments to production upon release

### ISSUE THREAD

**Issue by kabilar** [lincbrain/linc-archive#222]

**Comment by kabilar** [comment]
Hi @aaronkanzer, has this issue been completed?  From what I understand, we submit pull requests to `master` and then to `release`.  Upon merge to `release`, the UI is updated by Netlify.  How about the backend?  Thanks.

**Comment by aaronkanzer** [comment]
@kabilar Yes this is completed!

https://github.com/lincbrain/linc-archive/blob/master/.github/workflows/backend-production-deploy.yml#L7-L10

We have logic that invokes this GitHub Actions pipeline upon merge into `release`

**Comment by kabilar** [comment]
Great, thanks @aaronkanzer.  Just to clarify, since it is a manual trigger (`workflow_dispatch`), perhaps we can remove the `branches` filter?  Maybe I am misunderstanding something.
