### ISSUE TITLE
Create dockerized development environment for LINC and DANDI

### ISSUE THREAD

**Issue by kabilar** [lincbrain/linc-archive#27]
- [ ] https://github.com/lincbrain/linc-archive/pull/26
- [ ] https://github.com/dandi/dandi-archive/pull/1722

**Comment by aaronkanzer** [comment]
Update: https://github.com/dandi/dandi-archive/pull/1809 has been made to generalize code for `dandi` as well for https://github.com/lincbrain/linc-archive/pull/26
